version: '3.8'

services:
  api:
    build: ./api
    container_name: mobile-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - APP_VERSION=1.0.0
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: mobile-postgres
    environment:
      - POSTGRES_DB=mobileapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
