global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mobile-api-staging'
    static_configs:
      - targets: ['35.233.124.20:3000']
    metrics_path: '/health'
    scrape_interval: 10s
    
  - job_name: 'mobile-api-production'
    static_configs:
      - targets: ['34.38.164.180:3000']
    metrics_path: '/health'
    scrape_interval: 10s
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']