---
- name: Deploy Mobile API
  hosts: all
  become: no
  vars:
    api_version: "{{ lookup('env', 'API_VERSION') | default('latest', true) }}"

  tasks:
    - name: Check if user can run docker without sudo
      command: docker ps
      register: docker_check
      ignore_errors: true
      
    - name: Display Docker permissions status
      debug:
        var: docker_check
        
    - name: Create API directory
      file:
        path: /opt/mobile-api
        state: directory
        mode: '0755'
      register: dir_result
      ignore_errors: true
        
    - name: Display directory creation result
      debug:
        var: dir_result
        
    - name: Copy docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: /opt/mobile-api/docker-compose.yml
        mode: '0644'
      when: dir_result is succeeded
      
    - name: Run docker-compose with docker command
      shell: |
        cd /opt/mobile-api
        docker-compose pull
        docker-compose up -d
      when: docker_check is succeeded