---
- name: Test Connectivity and Environment
  hosts: all
  gather_facts: yes
  become: no
  
  tasks:
    - name: Display Ansible facts
      debug:
        var: ansible_distribution
        
    - name: Check Python version
      command: python3 --version
      register: python_version
      
    - name: Display Python version
      debug:
        var: python_version.stdout
        
    - name: Check if docker is installed
      command: which docker
      register: docker_path
      ignore_errors: true
      
    - name: Display Docker path
      debug:
        var: docker_path.stdout
        
    - name: Check if docker-compose is installed
      command: which docker-compose
      register: compose_path
      ignore_errors: true
      
    - name: Display docker-compose path
      debug:
        var: compose_path.stdout